### ISSUE TITLE
Package Boilerplate: Prep for V1

### ISSUE THREAD

**Issue by dblodorn** [public-assembly/assemble-package#1]
## Tasks

- [x] public-assembly/assemble-package#2
- [x] public-assembly/assemble-package#3
- [x] public-assembly/assemble-package#6
- [x] public-assembly/assemble-package#7
- [x] #11
- [x] #9
- [x] public-assembly/assemble-package#8
